name: 'Run Many'
description: 'Runs the correct NX projects'
author: 'Tycho Bokdam'
runs:
  using: 'node16'
  main: './dist/index.js'

inputs:
  tag:
    description: 'tag'
    required: false

  target:
    description: 'target'
    required: true

  affectedTarget:
    description: 'Use this target when checking affected projects'
    required: false

  index:
    description: 'index'
    required: false

  count:
    description: 'count'
    required: false

  parallel:
    description: 'parallel'
    required: false

  preTargets:
    description: 'Targets to run before'
    required: false

  postTargets:
    description: 'Targets to run after'
    required: false
