name: PR

# Run on all pull requests
on: [ pull_request ]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:

  pr:
    needs: [ prepare-env ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ env.DEPENDENCIES_CACHE }}-${{ hashFiles('yarn.lock') }}

      - name: yarn install
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v1
        if: ${{ inputs.set_shas == 'true' }}
        with:
          main-branch-name: master

      - name: GIT config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: nx affected:version
        uses: ./actions/run-many/action.yml
        with:
          target: version

      - name: nx affected:build
        uses: ./actions/run-many/action.yml
        with:
          target: build

      - name: nx affected:e2e
        uses: ./actions/run-many/action.yml
        with:
          target: e2e
          postTargets:
            - one
            - two
